// app/src/components/telemetry/TopBar.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useTelemetryStore } from '@/stores/telemetry'
import { carName } from '@/fh6-tel/lib/car-name'
import { CAR_CLASS_LABELS, DRIVETRAIN_LABELS } from '@/fh6-tel/lib/types'
import { ipc } from '@/fh6-tel/lib/ipc'
import { History, Settings } from '@lucide/vue'

withDefaults(defineProps<{
  useMph?: boolean
  tiresVisible?: boolean
  onSettings?: () => void
  onSessions?: () => void
  onToggleTires?: () => void
}>(), {
  useMph: true,
  tiresVisible: true,
})

const telemetry = useTelemetryStore()
const pkt = computed(() => telemetry.displayPacket)
const connected = computed(() => telemetry.isConnected)

const carLabel = computed(() => pkt.value ? carName(pkt.value.carOrdinal) : '—')
const isUnknown = computed(() => carLabel.value.startsWith('Car #'))
const classLabel = computed(() => pkt.value ? (CAR_CLASS_LABELS[pkt.value.carClass] ?? '?') : '—')
const piLabel = computed(() => pkt.value ? String(pkt.value.carPi) : '—')
const driveLabel = computed(() => pkt.value ? (DRIVETRAIN_LABELS[pkt.value.drivetrainType] ?? '?') : '—')

const copied = ref(false)
const version = ref('')

onMounted(async () => {
  version.value = await ipc.getAppVersion()
})

async function copyOrdinal() {
  if (!pkt.value || !isUnknown.value) return
  await navigator.clipboard.writeText(String(pkt.value.carOrdinal))
  copied.value = true
  setTimeout(() => { copied.value = false }, 1800)
}

const classBadgeColors: Record<string, string> = {
  X: 'text-red-500 border-red-900',
  S2: 'text-orange-500 border-orange-900',
  S1: 'text-yellow-500 border-yellow-900',
  A: 'text-green-500 border-green-900',
  B: 'text-blue-500 border-blue-900',
  C: 'text-purple-500 border-purple-900',
  D: 'text-[var(--tx-lo)] border-[var(--bd-subtle)]',
}
</script>

<template>
  <header class="flex items-center justify-between px-4 h-12 bg-[var(--bg-panel)] border-b border-[var(--bd-dim)] shrink-0">
    <div class="flex items-center gap-1.5">
      <span
        class="w-2 h-2 rounded-full transition-colors duration-300"
        :class="connected ? 'bg-green-500 shadow-[0_0_6px_#22c55e]' : 'bg-red-500'"
      />
      <span class="text-[0.85rem] font-bold tracking-wider text-[var(--tx-dim)]">
        {{ connected ? '实时遥测' : '等待连接…' }}
      </span>
    </div>

    <div class="flex items-center gap-1.5 min-w-0 overflow-hidden">
      <span
        class="text-[clamp(0.8rem,1.8vw,1rem)] font-semibold text-[var(--tx-mid)] whitespace-nowrap overflow-hidden text-ellipsis max-w-[clamp(80px,22vw,260px)]"
        :class="isUnknown ? 'text-[var(--tx-dim)] cursor-copy hover:text-[var(--tx-lo)]' : ''"
        :title="isUnknown ? `车辆ID: ${pkt?.carOrdinal} — 点击复制` : undefined"
        @click="copyOrdinal"
      >
        {{ copied ? '已复制!' : carLabel }}
      </span>
      <span
        class="text-[clamp(0.65rem,1.4vw,0.8rem)] font-bold px-1.5 py-[0.15rem] border rounded flex-shrink-0 whitespace-nowrap"
        :class="classBadgeColors[classLabel] ?? 'text-[var(--tx-lo)] border-[var(--bd-muted)]'"
      >
        {{ classLabel }}
      </span>
      <span class="text-[clamp(0.65rem,1.4vw,0.8rem)] font-bold px-1.5 py-[0.15rem] border border-[var(--bd-muted)] rounded text-[var(--tx-lo)] flex-shrink-0 whitespace-nowrap">
        {{ piLabel }}
      </span>
      <span class="text-[clamp(0.65rem,1.4vw,0.8rem)] font-bold px-1.5 py-[0.15rem] border border-[var(--bd-muted)] rounded text-[var(--tx-lo)] flex-shrink-0 whitespace-nowrap">
        {{ driveLabel }}
      </span>
    </div>

    <div class="flex items-center gap-1.5">
      <button
        class="fh6-action-button text-[0.68rem] font-black"
        :class="tiresVisible
          ? 'is-active'
          : ''"
        @click="onToggleTires?.()"
        :title="tiresVisible ? '隐藏轮胎数据' : '显示轮胎数据'"
      >胎</button>
      <button class="fh6-action-button" @click="onSessions?.()" title="历史会话">
        <History :size="14" />
      </button>
      <button class="fh6-action-button" @click="onSettings?.()" title="设置">
        <Settings :size="14" />
      </button>
      <span v-if="version" class="text-[0.7rem] text-[var(--tx-xdim)] tracking-wide px-[0.1rem]">v{{ version }}</span>
    </div>
  </header>
</template>

<style scoped>
.fh6-action-button {
  width: 1.75rem;
  height: 1.75rem;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  border: 1px solid var(--bd-muted);
  border-radius: 6px;
  background: var(--bg-panel);
  color: var(--tx-xdim);
  cursor: pointer;
  font-size: 0.72rem;
  font-weight: 800;
  line-height: 1;
  transition: border-color 120ms ease, background-color 120ms ease, color 120ms ease, transform 120ms ease;
}

.fh6-action-button :deep(svg) {
  display: block;
}

.fh6-action-button:hover {
  border-color: var(--bd-strong);
  background: var(--bg-elevated);
  color: var(--tx-mid);
}

.fh6-action-button:active {
  transform: scale(0.96);
}

.fh6-action-button.is-active {
  border-color: var(--ac);
  color: var(--ac);
  background: color-mix(in srgb, var(--ac) 8%, var(--bg-panel));
}
</style>

// app/src/fh6-tel/lib/components/TopBar.svelte
<script lang="ts">
  import { ipc } from '$lib/ipc';
  import { isConnected, displayPacket } from '$lib/stores/telemetry';
  import { carName } from '$lib/car-name';
  import { CAR_CLASS_LABELS, DRIVETRAIN_LABELS } from '$lib/types';

  let { useMph = true, onSettings, onSessions, tiresVisible = true, onToggleTires }: {
    useMph: boolean;
    onSettings: () => void;
    onSessions: () => void;
    tiresVisible?: boolean;
    onToggleTires?: () => void;
  } = $props();

  let pkt = $derived($displayPacket);
  let connected = $derived($isConnected);
  let carLabel = $derived(pkt ? carName(pkt.carOrdinal) : '—');
  let isUnknown = $derived(pkt ? carLabel.startsWith('Car #') : false);
  let classLabel = $derived(pkt ? (CAR_CLASS_LABELS[pkt.carClass] ?? '?') : '—');
  let piLabel = $derived(pkt ? String(pkt.carPi) : '—');
  let driveLabel = $derived(pkt ? (DRIVETRAIN_LABELS[pkt.drivetrainType] ?? '?') : '—');

  let copied = $state(false);
  let version = $state('');
  ipc.getAppVersion().then(v => { version = v; });

  async function copyOrdinal() {
    if (!pkt || !isUnknown) return;
    await navigator.clipboard.writeText(String(pkt.carOrdinal));
    copied = true;
    setTimeout(() => { copied = false; }, 1800);
  }
</script>

<header class="topbar">
  <div class="status">
    <span class="dot" class:live={connected}></span>
    <span class="label">{connected ? '实时遥测' : '等待连接…'}</span>
  </div>

  <div class="car-info">
    <!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
    <span
      class="car-name"
      class:unknown={isUnknown}
      onclick={copyOrdinal}
      title={isUnknown ? `车辆ID: ${pkt?.carOrdinal} — 点击复制` : undefined}
    >
      {copied ? '已复制!' : carLabel}
    </span>
    <span class="badge class-badge" data-class={classLabel}>{classLabel}</span>
    <span class="badge">{piLabel}</span>
    <span class="badge">{driveLabel}</span>
  </div>

  <div class="controls">
    <button
      class="panel-chip"
      class:active={tiresVisible}
      onclick={onToggleTires}
      title={tiresVisible ? '隐藏轮胎数据' : '显示轮胎数据'}
    >轮胎</button>
    <button class="icon-btn" onclick={onSessions} title="历史会话">⏱</button>
    <button class="icon-btn" onclick={onSettings} title="设置">⚙</button>
    {#if version}<span class="version">v{version}</span>{/if}
  </div>
</header>

<style>
  .topbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 1rem;
    height: 2.5rem;
    background: var(--bg-panel);
    border-bottom: 1px solid var(--bd-dim);
    flex-shrink: 0;
  }
  .status { display: flex; align-items: center; gap: 0.4rem; }
  .dot {
    width: 8px; height: 8px; border-radius: 50%;
    background: #ef4444;
    transition: background 0.3s;
  }
  .dot.live { background: #22c55e; box-shadow: 0 0 6px #22c55e; }
  .label { font-size: 0.7rem; font-weight: 700; letter-spacing: 0.1em; color: var(--tx-dim); }
  .car-info { display: flex; align-items: center; gap: 0.4rem; min-width: 0; overflow: hidden; }
  .car-name {
    font-size: clamp(0.7rem, 1.6vw, 0.85rem);
    font-weight: 600;
    color: var(--tx-mid);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    max-width: clamp(80px, 22vw, 260px);
  }
  .car-name.unknown { color: var(--tx-dim); cursor: copy; }
  .car-name.unknown:hover { color: var(--tx-lo); }
  .badge {
    font-size: clamp(0.55rem, 1.2vw, 0.65rem);
    font-weight: 700;
    padding: 0.1rem 0.35rem;
    border: 1px solid var(--bd-muted);
    border-radius: 3px;
    color: var(--tx-lo);
    flex-shrink: 0;
    white-space: nowrap;
  }
  /* Class badge colours are semantic — stay fixed across themes */
  .class-badge[data-class="X"]  { color: #ef4444; border-color: #7f1d1d; }
  .class-badge[data-class="S2"] { color: #f97316; border-color: #7c2d12; }
  .class-badge[data-class="S1"] { color: #eab308; border-color: #713f12; }
  .class-badge[data-class="A"]  { color: #22c55e; border-color: #14532d; }
  .class-badge[data-class="B"]  { color: #3b82f6; border-color: #1e3a5f; }
  .class-badge[data-class="C"]  { color: #a855f7; border-color: #4c1d95; }
  .class-badge[data-class="D"]  { color: var(--tx-lo); border-color: var(--bd-subtle); }
  .controls { display: flex; align-items: center; gap: 0.25rem; }
  .version { font-size: 0.6rem; color: var(--tx-xdim); letter-spacing: 0.03em; padding: 0 0.1rem; }
  .icon-btn {
    background: none; border: none; cursor: pointer;
    font-size: 1rem; color: var(--tx-dim); padding: 0.25rem 0.5rem;
    border-radius: 4px;
  }
  .icon-btn:hover { background: var(--bg-elevated); color: var(--tx-mid); }
  .panel-chip {
    background: none;
    border: 1px solid var(--bd-muted);
    color: var(--tx-xdim);
    font-size: 0.5rem;
    font-weight: 700;
    letter-spacing: 0.08em;
    padding: 0.15rem 0.4rem;
    border-radius: 3px;
    cursor: pointer;
  }
  .panel-chip.active {
    border-color: var(--ac);
    color: var(--ac);
  }

  .panel-chip:hover { color: var(--tx-mid); }
</style>
